name: vlslice
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - flask=2.1.3
  - flask-session=0.4.0
  - numpy=1.22.4
  - pandas=1.4.4
  - pillow=9.0.1
  - pip=23.0.1
  - python=3.10.9
  - pytorch=1.11.0
  - pyyaml=6.0
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - transformers=4.18.0
  - pip:
    - tokenizers==0.12.1
