flask:
  host: 0.0.0.0
data:
  path: /home/ubuntu/data/
  exclude_classes:
    - human eye
    - human skull
    - human head
    - human face
    - human mouth
    - human ear
    - human nose
    - human hair
    - human hand
    - human foot
    - human arm
    - human leg
    - human beard
    - human body
    - tire
    - wheel
model:
  version: openai/clip-vit-base-patch16
  device: cpu
dev: True
