flask:
  host: 0.0.0.0
  port: 5000
  debug: false
data:
  imgs_npy: ./static/imgs.npy
  lbls_npy: ./static/lbls.npy
  embs_npy: ./static/embs.npy
  exclude_classes:
    - human eye
    - human skull
    - human head
    - human face
    - human mouth
    - human ear
    - human nose
    - human hair
    - human hand
    - human foot
    - human arm
    - human leg
    - human beard
    - human body
    - tire
    - wheel
    - window
    - door
    - door handle
    - vehicle registration plate
model:
  name: hf_clip
  config:
    version: openai/clip-vit-base-patch16
    device: cpu
